### ISSUE TITLE
Support Kotlin 1.8.0 and KSP 1.8.0-1.0.8

### ISSUE THREAD

**Issue by PatilShreyas** [tschuchortdev/kotlin-compile-testing#351] opened 2023-02-19 11:17 UTC
Currently, tests are failing if targetted to a project using Kotlin 1.8.0 and KSP 1.8.0-1.0.8

**Comment by 3flex** [comment] 2023-02-23 03:12
Duplicate of #336

**Comment by PatilShreyas** [comment] 2023-02-23 03:29
Thanks, I was unable to find that one. Closing this then!

**Closed** 2023-02-23 03:29 UTC
