### ISSUE TITLE
Error when try use compile

### ISSUE THREAD

**Issue by uziasferreirazup** [tschuchortdev/kotlin-compile-testing#73] opened 2020-11-11 14:24 UTC
```kotlin
java.lang.NoSuchMethodError: okio.Okio.sink$default(Ljava/io/File;ZILjava/lang/Object;)Lokio/Sink;

	at com.tschuchort.compiletesting.SourceFile$Companion$new$1.writeIfNeeded$kotlin_compile_testing(SourceFile.kt:41)
	at com.tschuchort.compiletesting.KotlinCompilation.compile(KotlinCompilation.kt:606)
```

the code:
```kotlin

    private fun prepareCompilation(vararg sourceFiles: SourceFile): KotlinCompilation {
        return KotlinCompilation()
            .apply {
                workingDir = temporaryFolder.root
                annotationProcessors = listOf(BeagleInternalAnnotationProcessor())
                inheritClassPath = true
                sources = sourceFiles.asList()
                verbose = false
            }
    }

    private fun compile(vararg sourceFiles: SourceFile): KotlinCompilation.Result {
        return prepareCompilation(*sourceFiles).compile()
    }
```

**Comment by tschuchortdev** [comment] 2020-11-11 14:45
This looks like some kind of binary incompatibility problem. Do you use Retrofit? It depends on Okio, so it might pull in a newer/older version that is incompatible. There is probably a Gradle task that can tell you where transitive dependencies on Okio come from and which version they pull in, but I don't know it off the top of my head.

**Comment by uziasferreirazup** [comment] 2020-11-11 14:57
I have only the dependencies to make a processor, nothing linked to the retrofit :(

**Comment by uziasferreirazup** [comment] 2020-11-11 15:07
@tschuchortdev there is some reason to use     implementation 'com.github.tschuchortdev:kotlin-compile-testing:1.3.1'
and not:
    testImplementation 'com.github.tschuchortdev:kotlin-compile-testing:1.3.1' ??

**Comment by uziasferreirazup** [comment] 2020-11-11 15:15
`implementation 'com.github.tschuchortdev:kotlin-compile-testing:1.3.1'` I put in `implementation` and the test works ok, but if i put in `testImplementation` the erros appears

**Comment by tschuchortdev** [comment] 2020-11-11 16:27
What other dependencies do you have? Can you upload a project to reproduce the problem?

**Comment by uziasferreirazup** [comment] 2020-11-12 12:24
I have an open-source project and a module called internal-processer: https://github.com/ZupIT/beagle/tree/tests/add-test-to-processor/android/internal-processor

**Comment by tschuchortdev** [comment] 2020-11-12 17:23
Hmm, it is obvious to me that there is some type of dependency conflict here, but the fact that it only occurs when using `testImplementation` is very curious. I can't see anything in your Gradle files that would hint at a problem. I suspect that this is a problem with your specific project configuration and not the library itself. Unfortunately, I don't know much about Gradle so I can't really help you. You should try to find out which libraries are on the classpath and where they come from: https://stackoverflow.com/questions/21311727/gradle-how-to-display-where-a-dependency-conflict-arises 
The order of dependencies on the classpath is important as it determines the precedence; perhaps that's the root of the problem. If `dependencyInsight` is not helpful you need to look at the runtime classpath (my library does this using classgraph). 

Do let me know if you find out what the problem was and you can of course reopen the issue if it does turn out to be a problem that needs to be fixed in the library itself.

**Closed by tschuchortdev** 2020-11-12 17:23 UTC
